name: 'BrowserStack Test'
on:
  push:
  pull_request:
  # schedule:
  #   - cron: '0 3 * * *'
jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

# The next 3 steps are for building the web application to be tested and starting the web server on the runner environment
      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Building web application to be tested'
        run: npm install

      - name: 'Running application under test'
        run: ./node_modules/.bin/http-server -p 8099 &

      - name: 'Installing browserstack-cypress-cli'
        run: npm install -g browserstack-cypress-cli

      - name: 'Testing Artemis'  
        run: browserstack-cypress run --headed --env BROWSERSTACK_LOCAL=false

      # - name: 'Testing Artemis'  
      #   run: browserstack-cypress run --headed --env BASE_URL=https://admin.artemis.accessify.cloud BROWSERSTACK_LOCAL=false

      # - name: 'Testing Development Artemis'  
      #   run:  browserstack-cypress run --headed --env BASE_URL=https://admin.development.artemis.accessify.cloud BROWSERSTACK_LOCAL=false

      # - name: 'Testing Hermes'  
      #   run:  browserstack-cypress run --headed --env BASE_URL=https://admin.hermes.accessify.cloud BROWSERSTACK_LOCAL=false